dist: trusty
sudo: required
language: cpp
compiler: clang
script: mkdir build && cd build && cmake .. && make -j4 && make test
matrix:
  include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
        - george-edison55-precise-backports
        packages:
        - clang
        - cmake-data
        - cmake
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"